name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk
          pip install buildozer

      - name: Build
        run: buildozer android debug
